# Generated by Django 5.0 on 2025-09-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="allow_contact",
            field=models.BooleanField(
                default=True, help_text="Allow recruiters to contact you directly"
            ),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="show_education",
            field=models.BooleanField(
                default=True, help_text="Show your education details to recruiters"
            ),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="show_links",
            field=models.BooleanField(
                default=True, help_text="Show your portfolio/social links to recruiters"
            ),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="show_skills",
            field=models.BooleanField(
                default=True, help_text="Show your skills to recruiters"
            ),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="show_work_experience",
            field=models.BooleanField(
                default=True, help_text="Show your work experience to recruiters"
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="profile_visible",
            field=models.BooleanField(
                default=True, help_text="Make your profile visible to recruiters"
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="show_email",
            field=models.BooleanField(
                default=True, help_text="Show your email address to recruiters"
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="show_phone",
            field=models.BooleanField(
                default=False, help_text="Show your phone number to recruiters"
            ),
        ),
    ]
