# Generated by Django 5.0 on 2025-09-27 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_jobseekerprofile_allow_contact_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="moderated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="moderated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="moderation_notes",
            field=models.TextField(blank=True, help_text="Admin notes for moderation"),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("flagged", "Flagged for Review"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("removed", "Removed"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
