# Generated by Django 4.2.24 on 2025-10-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude for map display', null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude for map display', null=True),
        ),
    ]
