# Generated by Django 5.0 on 2025-10-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_jobposting_latitude_jobposting_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("review", "Under Review"),
                    ("interview", "Interview"),
                    ("offer", "Offer Extended"),
                    ("closed", "Closed"),
                ],
                default="applied",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="status_notes",
            field=models.TextField(
                blank=True, help_text="Internal notes about application status"
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
